interface CountryInfo {
  code: string;
  name: string;
}

interface DurationInfo {
  departure: number;
  return: number;
  total: number;
}

interface ConversionInfo {
  EUR: number;
  NGN: number;
}

interface FareInfo {
  adults: number;
  children: number;
  infants: number;
}

interface PriceDropdownInfo {
  base_fare: number;
  fees: number;
}

interface BagsPriceInfo {
  "1": number;
  "2": number;
}

interface BagLimitInfo {
  hand_height: number;
  hand_length: number;
  hand_weight: number;
  hand_width: number;
  hold_dimensions_sum: number;
  hold_height: number;
  hold_length: number;
  hold_weight: number;
  hold_width: number;
  personal_item_height: number;
  personal_item_length: number;
  personal_item_weight: number;
  personal_item_width: number;
}

interface AvailabilityInfo {
  seats: number;
}

interface RouteInfo {
  id: string;
  combination_id: string;
  flyFrom: string;
  flyTo: string;
  cityFrom: string;
  cityCodeFrom: string;
  cityTo: string;
  cityCodeTo: string;
  local_departure: string;
  utc_departure: string;
  local_arrival: string;
  utc_arrival: string;
  airline: string;
  flight_no: number;
  operating_carrier: string;
  operating_flight_no: string;
  fare_basis: string;
  fare_category: string;
  fare_classes: string;
  fare_family: string;
  return: number;
  bags_recheck_required: boolean;
  vi_connection: boolean;
  guarantee: boolean;
  equipment: null | string;
  vehicle_type: string;
}

export interface FlightInfo {
  id: string;
  flyFrom: string;
  flyTo: string;
  cityFrom: string;
  cityCodeFrom: string;
  cityTo: string;
  cityCodeTo: string;
  countryFrom: CountryInfo;
  countryTo: CountryInfo;
  local_departure: string;
  utc_departure: string;
  local_arrival: string;
  utc_arrival: string;
  nightsInDest: null | number;
  quality: number;
  distance: number;
  duration: DurationInfo;
  price: number;
  conversion: ConversionInfo;
  fare: FareInfo;
  price_dropdown: PriceDropdownInfo;
  bags_price: BagsPriceInfo;
  baglimit: BagLimitInfo;
  availability: AvailabilityInfo;
  airlines: string[];
  route: RouteInfo[];
  booking_token: string;
  facilitated_booking_available: boolean;
  pnr_count: number;
  has_airport_change: boolean;
  technical_stops: number;
  throw_away_ticketing: boolean;
  hidden_city_ticketing: boolean;
  virtual_interlining: boolean;
}

export interface SearchFlightsResponse {
  search_id: string;
  currency: string;
  fx_rate: number;
  data: FlightInfo[];
  _results: number;
}

export enum SeatAvailability {
  available = "available",
  unavailable = "unavailable",
}
export interface SeatInterface {
  column: string;
  features: string[];
  name: string;
  price: {
    amount: string;
    base: string;
    currency: string;
    merchant: string;
    service: string;
    service_flat: string;
  };
  seat_class: string;
  state: string;
  type: string;
}

export interface SeatRowInterface {
  row_number: number;
  seat_groups: SeatInterface[][];
}

export const mockRows = [
  {
    row_number: 30,
    seat_groups: [
      [
        {
          column: "A",
          features: ["window"],
          name: "30-A",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "B",
          features: [],
          name: "30-B",
          price: {
            amount: "248",
            base: "236",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "C",
          features: ["aisle"],
          name: "30-C",
          price: {
            amount: "261",
            base: "249",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
      ],
      [
        {
          column: "D",
          features: ["aisle"],
          name: "30-D",
          price: {
            amount: "261",
            base: "249",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "E",
          features: [],
          name: "30-E",
          price: {
            amount: "240",
            base: "228",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "F",
          features: ["aisle"],
          name: "30-F",
          price: {
            amount: "261",
            base: "249",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
      ],
      [
        {
          column: "J",
          features: ["aisle"],
          name: "30-J",
          price: {
            amount: "261",
            base: "249",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "K",
          features: [],
          name: "30-K",
          price: {
            amount: "248",
            base: "236",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "L",
          features: ["window"],
          name: "30-L",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
    ],
  },
  {
    row_number: 31,
    seat_groups: [
      [
        {
          column: "A",
          features: ["window"],
          name: "31-A",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "B",
          features: [],
          name: "31-B",
          price: {
            amount: "218",
            base: "206",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "C",
          features: ["aisle"],
          name: "31-C",
          price: {
            amount: "229",
            base: "217",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
      ],
      [
        {
          column: "D",
          features: ["aisle"],
          name: "31-D",
          price: {
            amount: "229",
            base: "217",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "E",
          features: [],
          name: "31-E",
          price: {
            amount: "207",
            base: "195",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "F",
          features: ["aisle"],
          name: "31-F",
          price: {
            amount: "229",
            base: "217",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
      ],
      [
        {
          column: "J",
          features: ["aisle"],
          name: "31-J",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "K",
          features: [],
          name: "31-K",
          price: {
            amount: "218",
            base: "206",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "L",
          features: ["window"],
          name: "31-L",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
    ],
  },
  {
    row_number: 32,
    seat_groups: [
      [
        {
          column: "A",
          features: ["window"],
          name: "32-A",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "B",
          features: [],
          name: "32-B",
          price: {
            amount: "46",
            base: "34",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "C",
          features: ["aisle"],
          name: "32-C",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "D",
          features: ["aisle"],
          name: "32-D",
          price: {
            amount: "229",
            base: "217",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "E",
          features: [],
          name: "32-E",
          price: {
            amount: "207",
            base: "195",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "F",
          features: ["aisle"],
          name: "32-F",
          price: {
            amount: "229",
            base: "217",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
      ],
      [
        {
          column: "J",
          features: ["aisle"],
          name: "32-J",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "K",
          features: [],
          name: "32-K",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "L",
          features: ["window"],
          name: "32-L",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
    ],
  },
  {
    row_number: 33,
    seat_groups: [
      [
        {
          column: "A",
          features: ["window"],
          name: "33-A",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "B",
          features: [],
          name: "33-B",
          price: {
            amount: "46",
            base: "34",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "C",
          features: ["aisle"],
          name: "33-C",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "D",
          features: ["aisle"],
          name: "33-D",
          price: {
            amount: "229",
            base: "217",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "E",
          features: [],
          name: "33-E",
          price: {
            amount: "207",
            base: "195",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "F",
          features: ["aisle"],
          name: "33-F",
          price: {
            amount: "229",
            base: "217",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
      ],
      [
        {
          column: "J",
          features: ["aisle"],
          name: "33-J",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "K",
          features: [],
          name: "33-K",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "L",
          features: ["window"],
          name: "33-L",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
    ],
  },
  {
    row_number: 34,
    seat_groups: [
      [
        {
          column: "A",
          features: ["window"],
          name: "34-A",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "B",
          features: [],
          name: "34-B",
          price: {
            amount: "46",
            base: "34",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "C",
          features: ["aisle"],
          name: "34-C",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "D",
          features: ["aisle"],
          name: "34-D",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "E",
          features: [],
          name: "34-E",
          price: {
            amount: "46",
            base: "34",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "F",
          features: ["aisle"],
          name: "34-F",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
      ],
      [
        {
          column: "J",
          features: ["aisle"],
          name: "34-J",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "K",
          features: [],
          name: "34-K",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "L",
          features: ["window"],
          name: "34-L",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
    ],
  },
  {
    row_number: 35,
    seat_groups: [
      [
        {
          column: "A",
          features: ["window"],
          name: "35-A",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "B",
          features: [],
          name: "35-B",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "C",
          features: ["aisle"],
          name: "35-C",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "D",
          features: ["aisle"],
          name: "35-D",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "E",
          features: [],
          name: "35-E",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "F",
          features: ["aisle"],
          name: "35-F",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
      ],
      [
        {
          column: "J",
          features: ["aisle"],
          name: "35-J",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "K",
          features: [],
          name: "35-K",
          price: {
            amount: "46",
            base: "34",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "L",
          features: ["window"],
          name: "35-L",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
    ],
  },
  {
    row_number: 36,
    seat_groups: [
      [
        {
          column: "A",
          features: ["window"],
          name: "36-A",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "B",
          features: [],
          name: "36-B",
          price: {
            amount: "46",
            base: "34",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "C",
          features: ["aisle"],
          name: "36-C",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
      ],
      [
        {
          column: "D",
          features: ["aisle"],
          name: "36-D",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "E",
          features: [],
          name: "36-E",
          price: {
            amount: "46",
            base: "34",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "F",
          features: ["aisle"],
          name: "36-F",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
      ],
      [
        {
          column: "J",
          features: ["aisle"],
          name: "36-J",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "K",
          features: [],
          name: "36-K",
          price: {
            amount: "46",
            base: "34",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "L",
          features: ["window"],
          name: "36-L",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
    ],
  },
  {
    row_number: 37,
    seat_groups: [
      [
        {
          column: "A",
          features: ["window"],
          name: "37-A",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "B",
          features: [],
          name: "37-B",
          price: {
            amount: "46",
            base: "34",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "C",
          features: ["aisle"],
          name: "37-C",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
      ],
      [
        {
          column: "D",
          features: ["aisle"],
          name: "37-D",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "E",
          features: [],
          name: "37-E",
          price: {
            amount: "46",
            base: "34",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "F",
          features: ["aisle"],
          name: "37-F",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "J",
          features: ["aisle"],
          name: "37-J",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "K",
          features: [],
          name: "37-K",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "L",
          features: ["window"],
          name: "37-L",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
    ],
  },
  {
    row_number: 38,
    seat_groups: [
      [
        {
          column: "A",
          features: ["window"],
          name: "38-A",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "B",
          features: [],
          name: "38-B",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "C",
          features: ["aisle"],
          name: "38-C",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
      ],
      [
        {
          column: "D",
          features: ["aisle"],
          name: "38-D",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "E",
          features: [],
          name: "38-E",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "F",
          features: ["aisle"],
          name: "38-F",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
      ],
      [
        {
          column: "J",
          features: ["aisle"],
          name: "38-J",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "K",
          features: [],
          name: "38-K",
          price: {
            amount: "46",
            base: "34",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "L",
          features: ["window"],
          name: "38-L",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
    ],
  },
  {
    row_number: 39,
    seat_groups: [
      [
        {
          column: "A",
          features: ["window"],
          name: "39-A",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "B",
          features: [],
          name: "39-B",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "C",
          features: ["aisle"],
          name: "39-C",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "D",
          features: ["aisle"],
          name: "39-D",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "E",
          features: [],
          name: "39-E",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "F",
          features: ["aisle"],
          name: "39-F",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "J",
          features: ["aisle"],
          name: "39-J",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "K",
          features: [],
          name: "39-K",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "L",
          features: ["window"],
          name: "39-L",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
    ],
  },
  {
    row_number: 40,
    seat_groups: [
      [
        {
          column: "A",
          features: ["window"],
          name: "40-A",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "B",
          features: [],
          name: "40-B",
          price: {
            amount: "12",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "C",
          features: ["aisle"],
          name: "40-C",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "J",
          features: ["aisle"],
          name: "40-J",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "K",
          features: [],
          name: "40-K",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "L",
          features: ["window"],
          name: "40-L",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
    ],
  },
  {
    row_number: 42,
    seat_groups: [
      [
        {
          column: "A",
          features: ["window", "emergency_exit"],
          name: "42-A",
          price: {
            amount: "265",
            base: "253",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "B",
          features: ["emergency_exit"],
          name: "42-B",
          price: {
            amount: "276",
            base: "264",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "C",
          features: ["aisle", "emergency_exit"],
          name: "42-C",
          price: {
            amount: "287",
            base: "275",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
      ],
      [
        {
          column: "D",
          features: ["aisle"],
          name: "42-D",
          price: {
            amount: "261",
            base: "249",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "E",
          features: [],
          name: "42-E",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "F",
          features: ["aisle"],
          name: "42-F",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "J",
          features: ["aisle", "emergency_exit"],
          name: "42-J",
          price: {
            amount: "287",
            base: "275",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "K",
          features: ["emergency_exit"],
          name: "42-K",
          price: {
            amount: "276",
            base: "264",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "L",
          features: ["window", "emergency_exit"],
          name: "42-L",
          price: {
            amount: "265",
            base: "253",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
      ],
    ],
  },
  {
    row_number: 43,
    seat_groups: [
      [
        {
          column: "A",
          features: ["window"],
          name: "43-A",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "B",
          features: [],
          name: "43-B",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "C",
          features: ["aisle"],
          name: "43-C",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
      ],
      [
        {
          column: "D",
          features: ["aisle"],
          name: "43-D",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "E",
          features: [],
          name: "43-E",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "F",
          features: ["aisle"],
          name: "43-F",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
      ],
      [
        {
          column: "J",
          features: ["aisle"],
          name: "43-J",
          price: {
            amount: "229",
            base: "217",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "K",
          features: [],
          name: "43-K",
          price: {
            amount: "218",
            base: "206",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "L",
          features: ["window"],
          name: "43-L",
          price: {
            amount: "229",
            base: "217",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
      ],
    ],
  },
  {
    row_number: 44,
    seat_groups: [
      [
        {
          column: "A",
          features: ["window"],
          name: "44-A",
          price: {
            amount: "53",
            base: "41",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "B",
          features: [],
          name: "44-B",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "C",
          features: ["aisle"],
          name: "44-C",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
      ],
      [
        {
          column: "D",
          features: ["aisle"],
          name: "44-D",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "E",
          features: [],
          name: "44-E",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "F",
          features: ["aisle"],
          name: "44-F",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
      ],
      [
        {
          column: "J",
          features: ["aisle"],
          name: "44-J",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "K",
          features: [],
          name: "44-K",
          price: {
            amount: "12",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "L",
          features: ["window"],
          name: "44-L",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
    ],
  },
  {
    row_number: 45,
    seat_groups: [
      [
        {
          column: "A",
          features: ["window"],
          name: "45-A",
          price: {
            amount: "53",
            base: "41",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "B",
          features: [],
          name: "45-B",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "C",
          features: ["aisle"],
          name: "45-C",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
      ],
      [
        {
          column: "D",
          features: ["aisle"],
          name: "45-D",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "E",
          features: [],
          name: "45-E",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "F",
          features: ["aisle"],
          name: "45-F",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
      ],
      [
        {
          column: "J",
          features: ["aisle"],
          name: "45-J",
          price: {
            amount: "63",
            base: "51",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "K",
          features: [],
          name: "45-K",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "L",
          features: ["window"],
          name: "45-L",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
    ],
  },
  {
    row_number: 46,
    seat_groups: [
      [
        {
          column: "A",
          features: ["window"],
          name: "46-A",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "B",
          features: [],
          name: "46-B",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "C",
          features: ["aisle"],
          name: "46-C",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "D",
          features: ["aisle"],
          name: "46-D",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "E",
          features: [],
          name: "46-E",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "F",
          features: ["aisle"],
          name: "46-F",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "J",
          features: ["aisle"],
          name: "46-J",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "K",
          features: [],
          name: "46-K",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "L",
          features: ["window"],
          name: "46-L",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
    ],
  },
  {
    row_number: 47,
    seat_groups: [
      [
        {
          column: "A",
          features: ["window"],
          name: "47-A",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "B",
          features: [],
          name: "47-B",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "C",
          features: ["aisle"],
          name: "47-C",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "D",
          features: ["aisle"],
          name: "47-D",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "E",
          features: [],
          name: "47-E",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "F",
          features: ["aisle"],
          name: "47-F",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "J",
          features: ["aisle"],
          name: "47-J",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "K",
          features: [],
          name: "47-K",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "L",
          features: ["window"],
          name: "47-L",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
    ],
  },
  {
    row_number: 48,
    seat_groups: [
      [
        {
          column: "A",
          features: ["window"],
          name: "48-A",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "B",
          features: [],
          name: "48-B",
          price: {
            amount: "12",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "C",
          features: ["aisle"],
          name: "48-C",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "D",
          features: ["aisle"],
          name: "48-D",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "E",
          features: [],
          name: "48-E",
          price: {
            amount: "12",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "F",
          features: ["aisle"],
          name: "48-F",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "J",
          features: ["aisle"],
          name: "48-J",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "K",
          features: [],
          name: "48-K",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "L",
          features: ["window"],
          name: "48-L",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
    ],
  },
  {
    row_number: 49,
    seat_groups: [
      [
        {
          column: "A",
          features: ["window"],
          name: "49-A",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "B",
          features: [],
          name: "49-B",
          price: {
            amount: "12",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "C",
          features: ["aisle"],
          name: "49-C",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "D",
          features: ["aisle"],
          name: "49-D",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "E",
          features: [],
          name: "49-E",
          price: {
            amount: "12",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "F",
          features: ["aisle"],
          name: "49-F",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "J",
          features: ["aisle"],
          name: "49-J",
          price: {
            amount: "12",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "K",
          features: [],
          name: "49-K",
          price: {
            amount: "12",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "L",
          features: ["window"],
          name: "49-L",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
    ],
  },
  {
    row_number: 50,
    seat_groups: [
      [
        {
          column: "A",
          features: ["window"],
          name: "50-A",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "B",
          features: [],
          name: "50-B",
          price: {
            amount: "12",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "C",
          features: ["aisle"],
          name: "50-C",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "D",
          features: ["aisle"],
          name: "50-D",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "E",
          features: [],
          name: "50-E",
          price: {
            amount: "12",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "F",
          features: ["aisle"],
          name: "50-F",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "J",
          features: ["aisle"],
          name: "50-J",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "K",
          features: [],
          name: "50-K",
          price: {
            amount: "12",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "L",
          features: ["window"],
          name: "50-L",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
    ],
  },
  {
    row_number: 51,
    seat_groups: [
      [
        {
          column: "A",
          features: ["window"],
          name: "51-A",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "B",
          features: [],
          name: "51-B",
          price: {
            amount: "12",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "C",
          features: ["aisle"],
          name: "51-C",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "D",
          features: ["aisle"],
          name: "51-D",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "E",
          features: [],
          name: "51-E",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "F",
          features: ["aisle"],
          name: "51-F",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "J",
          features: ["aisle"],
          name: "51-J",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "K",
          features: [],
          name: "51-K",
          price: {
            amount: "12",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "L",
          features: ["window"],
          name: "51-L",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
    ],
  },
  {
    row_number: 52,
    seat_groups: [
      [
        {
          column: "A",
          features: ["window"],
          name: "52-A",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "B",
          features: [],
          name: "52-B",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "C",
          features: ["aisle"],
          name: "52-C",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "D",
          features: ["aisle"],
          name: "52-D",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "E",
          features: [],
          name: "52-E",
          price: {
            amount: "12",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "12",
          },
          seat_class: "standard",
          state: "available",
          type: "seat",
        },
        {
          column: "F",
          features: ["aisle"],
          name: "52-F",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
      [
        {
          column: "J",
          features: ["aisle"],
          name: "52-J",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "K",
          features: [],
          name: "52-K",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "L",
          features: ["window"],
          name: "52-L",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
    ],
  },
  {
    row_number: 53,
    seat_groups: [
      [
        {
          column: "D",
          features: ["aisle"],
          name: "53-D",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "E",
          features: [],
          name: "53-E",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
        {
          column: "F",
          features: ["aisle"],
          name: "53-F",
          price: {
            amount: "0",
            base: "0",
            currency: "EUR",
            merchant: "0",
            service: "0",
            service_flat: "0",
          },
          seat_class: "standard",
          state: "unavailable",
          type: "seat",
        },
      ],
    ],
  },
];
