import { ISiteConfig } from "types";

export const Siteconfig: ISiteConfig = {
  name: "Thrillers Travels: Reach the Western World on Eagle's Wings",
  description:
    "Embark on a seamless journey with Thrillers Travels, your trusted partner for travel bookings, visa assistance, travel guide and opportunities to study and work abroad. Experience the thrill of stress-free travel document procurement, fly on eagle's wings to your dream western destination today!",
  ogImage: "/favicon.png",
  keywords: [
    "travel",
    "visa",
    "flight",
    "ticket",
    "japa",
    "Travel agency",
    "Visa assistance",
    "Study abroad programs",
    "Work abroad opportunities",
    "International travel booking",
    "Affordable travel packages",
    "Customized travel plans",
    "Travel to Western countries",
    "Travel guidance and advice",
    "Reliable travel agency",
    "Experienced travel agents",
    "Educational travel",
    "Immigration assistance",
    "Visa application process",
    "Thrillers Travels",
    "Student visas",
    "Work visas",
    "Migration services",
    "Personalized travel itinerary",
    "Worldwide travel services",
    "Best travel agency",
    "Travel advice and tips",
    "Professional visa assistance",
    "Travel and tour packages",
    "Comprehensive travel plans",
    "Guided tours",
    "Affordable vacation packages",
    "Immigration support services",
    "Expert travel planning",
    "Study and work abroad",
  ],
  url: ["thrillers.travels", "thrillerstravels.com"],

  links: {
    email: "info@thrillerstravels.com",
    github: "https://github.com/thrillerstravels",
    instagram: "instagram.com/thrillerstravels",
    linkedin: "linkedin.com/company/",
    twitter: "twitter.com/thrillerstravels",
  },
};
